### ISSUE TITLE
NullPointerEx occurred when exists image that TAG is none on local machine.

### ISSUE THREAD

**Issue by crossroad0201** [j5ik2o/docker-controller-scala#203]
## Problem

NullPointerEx occurred when exists image that TAG is none on local machine.

```
Exception encountered when invoking run on a nested suite.
java.lang.NullPointerException
	at java.lang.reflect.Array.getLength(Native Method)
	at scala.collection.ArrayOps$.contains$extension(ArrayOps.scala:683)
	at com.github.j5ik2o.dockerController.DockerControllerImpl.$anonfun$pullImageIfNotExists$1(DockerController.scala:199)
	at com.github.j5ik2o.dockerController.DockerControllerImpl.$anonfun$pullImageIfNotExists$1$adapted(DockerController.scala:191)
	at scala.collection.IterableOnceOps.exists(IterableOnce.scala:591)
	at scala.collection.IterableOnceOps.exists$(IterableOnce.scala:588)
	at scala.collection.AbstractIterable.exists(Iterable.scala:919)
	at com.github.j5ik2o.dockerController.DockerControllerImpl.existsImage(DockerController.scala:184)
	at com.github.j5ik2o.dockerController.DockerControllerImpl.pullImageIfNotExists(DockerController.scala:191)
```

'docker images'  result like this.

```
> docker images
REPOSITORY             TAG
example/foo-bar       <none> 
```

## Cause

On [DockerController#pullImageIfNotExists](https://github.com/j5ik2o/docker-controller-scala/blob/main/docker-controller-scala-core/src/main/scala/com/github/j5ik2o/dockerController/DockerController.scala#L191), `p.getRepoTags` is return null when the exists image's TAG is none.

## Suggest of solution

Add null check for result of`p.getRepoTags`.

**Comment by j5ik2o** [comment]
@crossroad0201 

Thanks for your feedback!

docker-controller-scala-*_2.13-1.8.16+1-4473f408-SNAPSHOT.jar

The modified version has been deployed as a snapshot.

Could you please try it in your environment with the version '1.8.16+1-4473f408-SNAPSHOT' in the dependency?

**Comment by crossroad0201** [comment]
@j5ik2o 
I was able to solve this problem by remove untagged(TAG=<none>) Docker images from local machine using `docker image prune` command.

Untagged images are rarely created, so it seems good to remove such images using `docker image prune` command.
So I think unnecessary to support this library.

The changes in the SNAPSHOT do not seem to have anything todo with the problem I reported.
But, the changes looks good idea, so I think you can merge them.

Thankyou.
